GET http://localhost/project/example-app/public/api/orders

###

POST http://localhost/project/example-app/public/api/orders HTTP/1.1
Content-Type: application/json

{
    "user_id": 1,
    "status": "late"
}

### 

PUT http://localhost/project/example-app/public/api/orders/2
Content-Type: application/json

{
    "user_id": 1,
    "status": "late (updated)"
}


### 

DELETE http://localhost/project/example-app/public/api/orders/2




###
GET http://localhost/project/example-app/public/api/products

###

POST http://localhost/project/example-app/public/api/products HTTP/1.1
Content-Type: application/json

{
    "name": "test",
    "merchant_id": 2,
    "price": 200,
    "status": "new"
}